
/*
	TITLE: 		  POPULATE DIMENSIONS (ACCOUNTING)
	USED FOR: 	ORACLE BUSINESS INTELLIGENCE
	CREATED BY: TOTZ SARSONAS (Junior Software Developer)
	DATE:		1/23/2017
*/

--BI_TIME_DIM START
DROP TABLE BIADMIN.BI_TIME_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_TIME_DIM
(
  TIME_CODE      NUMBER(12) PRIMARY KEY,
  CALENDAR_DATE  DATE                           NOT NULL,
  YEAR_NO        NUMBER(4)                      NOT NULL,
  QUARTER_NO     NUMBER(1)                      NOT NULL,
  MONTH_NO       NUMBER(2)                      NOT NULL,
  MONTH_NAME     VARCHAR2(20 BYTE)              NOT NULL,
  WEEK_NO        NUMBER(1)                      NOT NULL,
  DATE_OF_MONTH  NUMBER(2)                      NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--BI_TIME_DIM END

--######################
--######################

--BI_BANK_DIM START
DROP TABLE BIADMIN.BI_BANK_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_BANK_DIM
(
  BANK_KEY       NUMBER PRIMARY KEY,
  BANK_CD        VARCHAR2(3 BYTE)               NOT NULL,
  BANK_NAME      VARCHAR2(100 BYTE)             NOT NULL,
  USER_ID        VARCHAR2(8 BYTE)               NOT NULL,
  LAST_UPDATE    DATE                           NOT NULL,
  BANK_SNAME     VARCHAR2(10 BYTE)              NOT NULL,
  REMARKS        VARCHAR2(4000 BYTE),
  CPI_REC_NO     NUMBER(12),
  CPI_BRANCH_CD  VARCHAR2(2 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_BANK_DIM;

INSERT INTO BI_BANK_DIM (SELECT ROWNUM AS BANK_KEY, A.* FROM GIAC_BANKS A);

--BI_BANK_DIM END

--######################
--######################

--BI_CHART_OF_ACCTS_DIM START
DROP TABLE BIADMIN.BI_CHART_OF_ACCTS_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CHART_OF_ACCTS_DIM
(
  COA_KEY           NUMBER PRIMARY KEY,
  GL_ACCT_ID        NUMBER(6)                   NOT NULL,
  GL_ACCT_CATEGORY  NUMBER(1)                   NOT NULL,
  GL_SUB_ACCT_1     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_2     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_3     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_4     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_5     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_6     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_7     NUMBER(2)                   NOT NULL,
  GL_ACCT_NAME      VARCHAR2(100 BYTE)          NOT NULL,
  GL_ACCT_SNAME     VARCHAR2(35 BYTE)           NOT NULL,
  SUB_ACCT_2_TAG    VARCHAR2(1 BYTE)            NOT NULL,
  SUB_ACCT_3_TAG    VARCHAR2(1 BYTE)            NOT NULL,
  SUB_ACCT_4_TAG    VARCHAR2(1 BYTE)            NOT NULL,
  SUB_ACCT_5_TAG    VARCHAR2(1 BYTE)            NOT NULL,
  SUB_ACCT_6_TAG    VARCHAR2(1 BYTE)            NOT NULL,
  SUB_ACCT_7_TAG    VARCHAR2(1 BYTE)            NOT NULL,
  LEAF_TAG          VARCHAR2(1 BYTE)            NOT NULL,
  GL_CONTROL_ACCT   NUMBER(2)                   NOT NULL,
  GSLT_SL_TYPE_CD   VARCHAR2(2 BYTE),
  DR_CR_TAG         VARCHAR2(1 BYTE),
  ACCT_TYPE         VARCHAR2(1 BYTE),
  USER_ID           VARCHAR2(8 BYTE)            NOT NULL,
  LAST_UPDATE       DATE                        NOT NULL,
  CPI_REC_NO        NUMBER(12),
  CPI_BRANCH_CD     VARCHAR2(2 BYTE),
  REF_ACCT_CD       VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_CHART_OF_ACCTS_DIM;

INSERT INTO BI_CHART_OF_ACCTS_DIM SELECT ROWNUM AS COA_KEY, A.* FROM GIAC_CHART_OF_ACCTS A;

--BI_CHART_OF_ACCTS_DIM END

--######################
--######################

--BI_CURRENCY_DIM START

DROP TABLE BIADMIN.BI_CURRENCY_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CURRENCY_DIM
(
  CURRENCY_KEY      NUMBER PRIMARY KEY,
  MAIN_CURRENCY_CD  NUMBER(2)                   NOT NULL,
  EFFECTIVITY_DATE  DATE                        NOT NULL,
  ACTIVE_FLAG       VARCHAR2(1 BYTE)            NOT NULL,
  CURRENCY_RT       NUMBER(12,9)                NOT NULL,
  INACTIVITY_DATE   DATE,
  REMARKS           VARCHAR2(4000 BYTE),
  USER_ID           VARCHAR2(8 BYTE)            NOT NULL,
  LAST_UPDATE       DATE                        NOT NULL,
  CPI_REC_NO        NUMBER(12),
  CPI_BRANCH_CD     VARCHAR2(2 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_CURRENCY_DIM;

INSERT INTO BI_CURRENCY_DIM SELECT ROWNUM AS CURRENCY_KEY, A.* FROM GIAC_CURRENCY A;

--BI_CURRENCY_DIM 

--######################
--######################

--BI_DCB_USERS_DIM START

DROP TABLE BIADMIN.BI_DCB_USERS_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_DCB_USERS_DIM
(
  DCB_USERS_KEY   NUMBER PRIMARY KEY,
  GIBR_BRANCH_CD  VARCHAR2(2 BYTE)              NOT NULL,
  GIBR_FUND_CD    VARCHAR2(3 BYTE)              NOT NULL,
  CASHIER_CD      NUMBER(3)                     NOT NULL,
  DCB_USER_ID     VARCHAR2(8 BYTE)              NOT NULL,
  VALID_TAG       VARCHAR2(1 BYTE),
  EFFECTIVITY_DT  DATE                          NOT NULL,
  EXPIRY_DT       DATE,
  PRINT_NAME      VARCHAR2(30 BYTE),
  USER_ID         VARCHAR2(8 BYTE)              NOT NULL,
  LAST_UPDATE     DATE                          NOT NULL,
  REMARKS         VARCHAR2(4000 BYTE),
  CPI_REC_NO      NUMBER(12),
  CPI_BRANCH_CD   VARCHAR2(2 BYTE),
  BANK_CD         VARCHAR2(3 BYTE),
  BANK_ACCT_CD    VARCHAR2(4 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_DCB_USERS_DIM;

INSERT INTO BI_DCB_USERS_DIM SELECT ROWNUM AS DCB_USERS_KEY, A.* FROM GIAC_DCB_USERS A;

--BI_DCB_USERS_DIM END

--######################
--######################

--BI_JV_TRANS_DIM START

DROP TABLE BIADMIN.BI_JV_TRANS_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_JV_TRANS_DIM
(
  JV_TRANS_KEY  NUMBER PRIMARY KEY,
  JV_TRAN_CD    VARCHAR2(3 BYTE)                NOT NULL,
  JV_TRAN_DESC  VARCHAR2(40 BYTE)               NOT NULL,
  JV_TRAN_TAG   VARCHAR2(2 BYTE)                NOT NULL,
  REMARKS       VARCHAR2(4000 BYTE),
  USER_ID       VARCHAR2(8 BYTE),
  LAST_UPDATE   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_JV_TRANS_DIM;

INSERT INTO BI_JV_TRANS_DIM SELECT ROWNUM JV_TRANS_KEY, A.* FROM GIAC_JV_TRANS A;

--BI_JV_TRANS_DIM END

--######################
--######################

--BI_BANK_ACCTS_DIM START

DROP TABLE BIADMIN.BI_BANK_ACCTS_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_BANK_ACCTS_DIM
(
  BANK_ACCTS_KEY     NUMBER PRIMARY KEY,
  BANK_CD            VARCHAR2(3 BYTE)           NOT NULL,
  BANK_ACCT_CD       VARCHAR2(4 BYTE)           NOT NULL,
  BANK_ACCT_TYPE     VARCHAR2(2 BYTE)           NOT NULL,
  BANK_ACCOUNT_FLAG  VARCHAR2(1 BYTE)           NOT NULL,
  OPENING_DATE       DATE                       NOT NULL,
  BANK_ACCT_NO       VARCHAR2(30 BYTE)          NOT NULL,
  GL_ACCT_ID         NUMBER(6)                  NOT NULL,
  SL_CD              NUMBER(12),
  CLOSING_DATE       DATE,
  USER_ID            VARCHAR2(8 BYTE)           NOT NULL,
  LAST_UPDATE        DATE                       NOT NULL,
  REMARKS            VARCHAR2(4000 BYTE),
  CPI_REC_NO         NUMBER(12),
  CPI_BRANCH_CD      VARCHAR2(2 BYTE),
  BRANCH_CD          VARCHAR2(2 BYTE),
  BRANCH             VARCHAR2(30 BYTE),
  BRANCH_BANK        VARCHAR2(30 BYTE)          NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_BANK_ACCTS_DIM;

INSERT INTO BI_BANK_ACCTS_DIM SELECT ROWNUM BANK_ACCTS_KEY, A.* FROM GIAC_BANK_ACCOUNTS A;

--BI_BANK_ACCTS_DIM END

--######################
--######################

--BI_BANK_BOOK_TRAN_DIM START

DROP TABLE BIADMIN.BI_BANK_BOOK_TRAN_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_BANK_BOOK_TRAN_DIM
(
  BANK_BOOK_TRAN_KEY  NUMBER PRIMARY KEY,
  BANK_CD             VARCHAR2(3 BYTE)          NOT NULL,
  BANK_TRAN_CD        VARCHAR2(5 BYTE)          NOT NULL,
  BANK_TRAN_DESC      VARCHAR2(40 BYTE),
  BOOK_TRAN_CD        VARCHAR2(5 BYTE),
  USER_ID             VARCHAR2(8 BYTE)          NOT NULL,
  LAST_UPDATE         DATE                      NOT NULL,
  REMARKS             VARCHAR2(4000 BYTE),
  BOOK_TRAN_DESC      VARCHAR2(40 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_BANK_BOOK_TRAN_DIM;

INSERT INTO BI_BANK_BOOK_TRAN_DIM SELECT ROWNUM BANK_BOOK_TRAN_KEY, A.* FROM GIAC_BANK_BOOK_TRAN A;

--BI_BANK_BOOK_TRAN_DIM END

--######################
--######################

--BI_PAYEES_DIM START

DROP TABLE BIADMIN.BI_PAYEES_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_PAYEES_DIM
(
  PAYEES_KEY          NUMBER PRIMARY KEY,
  PAYEE_NO            NUMBER(12)                NOT NULL,
  PAYEE_CLASS_CD      VARCHAR2(2 BYTE)          NOT NULL,
  PAYEE_LAST_NAME     VARCHAR2(500 BYTE)        NOT NULL,
  MAIL_ADDR1          VARCHAR2(50 BYTE)         NOT NULL,
  TIN                 VARCHAR2(30 BYTE)         NOT NULL,
  ALLOW_TAG           VARCHAR2(1 BYTE)          NOT NULL,
  PAYEE_FIRST_NAME    VARCHAR2(25 BYTE),
  PAYEE_MIDDLE_NAME   VARCHAR2(25 BYTE),
  MAIL_ADDR2          VARCHAR2(50 BYTE),
  MAIL_ADDR3          VARCHAR2(50 BYTE),
  CONTACT_PERS        VARCHAR2(50 BYTE),
  DESIGNATION         VARCHAR2(50 BYTE),
  PHONE_NO            VARCHAR2(40 BYTE),
  USER_ID             VARCHAR2(8 BYTE)          NOT NULL,
  LAST_UPDATE         DATE                      NOT NULL,
  REMARKS             VARCHAR2(4000 BYTE),
  CPI_REC_NO          NUMBER(12),
  CPI_BRANCH_CD       VARCHAR2(2 BYTE),
  FAX_NO              VARCHAR2(40 BYTE),
  SUN_NO              VARCHAR2(40 BYTE),
  SMART_NO            VARCHAR2(40 BYTE),
  GLOBE_NO            VARCHAR2(40 BYTE),
  CP_NO               VARCHAR2(40 BYTE),
  REF_PAYEE_CD        VARCHAR2(12 BYTE),
  BANK_ACCT_APP_DATE  DATE,
  BANK_ACCT_APP_TAG   VARCHAR2(1 BYTE),
  BANK_ACCT_APP_USER  VARCHAR2(8 BYTE),
  BANK_ACCT_NAME      VARCHAR2(100 BYTE),
  BANK_ACCT_NO        VARCHAR2(30 BYTE),
  BANK_ACCT_TYPE      VARCHAR2(2 BYTE),
  BANK_BRANCH         VARCHAR2(200 BYTE),
  BANK_CD             VARCHAR2(3 BYTE),
  GAP_TAG             VARCHAR2(5 BYTE),
  MASTER_PAYEE_NO     NUMBER(12)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_PAYEES_DIM;

INSERT INTO BI_PAYEES_DIM SELECT ROWNUM PAYEES_KEY, A.* FROM GIIS_PAYEES A

--BI_PAYEES_DIM END

--######################
--######################

--BI_SL_LISTS_DIM START
DROP TABLE BIADMIN.BI_SL_LISTS_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_SL_LISTS_DIM
(
  SL_LISTS_KEY   NUMBER PRIMARY KEY,
  FUND_CD        VARCHAR2(3 BYTE)               NOT NULL,
  SL_TYPE_CD     VARCHAR2(2 BYTE)               NOT NULL,
  SL_CD          NUMBER(12)                     NOT NULL,
  SL_NAME        VARCHAR2(600 BYTE)             NOT NULL,
  REMARKS        VARCHAR2(4000 BYTE),
  USER_ID        VARCHAR2(8 BYTE)               NOT NULL,
  LAST_UPDATE    DATE                           NOT NULL,
  CPI_REC_NO     NUMBER(12),
  CPI_BRANCH_CD  VARCHAR2(2 BYTE),
  ACTIVE_TAG     VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_SL_LISTS_DIM;

INSERT INTO BI_SL_LISTS_DIM SELECT ROWNUM SL_LISTS_KEY, A.* FROM GIAC_SL_LISTS A;

--BI_SL_LISTS_DIM END

--######################
--######################

--BI_SL_TYPES_DIM START

DROP TABLE BIADMIN.BI_SL_TYPES_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_SL_TYPES_DIM
(
  SL_TYPES_KEY   NUMBER PRIMARY KEY,
  SL_TYPE_CD     VARCHAR2(2 BYTE)               NOT NULL,
  SL_TYPE_NAME   VARCHAR2(100 BYTE)             NOT NULL,
  SL_TAG         VARCHAR2(1 BYTE)               NOT NULL,
  OS_FLAG        VARCHAR2(1 BYTE),
  USER_ID        VARCHAR2(8 BYTE)               NOT NULL,
  LAST_UPDATE    DATE                           NOT NULL,
  REMARKS        VARCHAR2(4000 BYTE),
  CPI_REC_NO     NUMBER(12),
  CPI_BRANCH_CD  VARCHAR2(2 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_SL_TYPES_DIM;

INSERT INTO BI_SL_TYPES_DIM SELECT ROWNUM SL_TYPES_KEY, A.* FROM GIAC_SL_TYPES A;

--BI_SL_TYPES_DIM END

--######################
--######################

--BI_TAXES_DIM START

DROP TABLE BIADMIN.BI_TAXES_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_TAXES_DIM
(
  TAXES_KEY         NUMBER PRIMARY KEY,
  FUND_CD           VARCHAR2(3 BYTE)            NOT NULL,
  TAX_CD            NUMBER(2)                   NOT NULL,
  TAX_NAME          VARCHAR2(100 BYTE)          NOT NULL,
  TAX_TYPE          VARCHAR2(1 BYTE)            NOT NULL,
  PRIORITY_CD       NUMBER(2)                   NOT NULL,
  GL_ACCT_ID        NUMBER(6)                   NOT NULL,
  GL_SUB_ACCT_1     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_2     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_3     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_4     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_5     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_6     NUMBER(2)                   NOT NULL,
  GL_SUB_ACCT_7     NUMBER(2)                   NOT NULL,
  GL_ACCT_CATEGORY  NUMBER(1),
  GL_CONTROL_ACCT   NUMBER(2),
  REMARKS           VARCHAR2(4000 BYTE),
  USER_ID           VARCHAR2(8 BYTE)            NOT NULL,
  LAST_UPDATE       DATE                        NOT NULL,
  CPI_REC_NO        NUMBER(12),
  CPI_BRANCH_CD     VARCHAR2(2 BYTE),
  COLUMN_NO         NUMBER(1)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_TAXES_DIM;

INSERT INTO BI_TAXES_DIM SELECT ROWNUM TAXES_KEY, A.* FROM GIAC_TAXES A

--BI_TAXES_DIM END

--######################
--######################

--BI_WHOLDING_TAXES_DIM START

DROP TABLE BIADMIN.BI_WHOLDING_TAXES_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_WHOLDING_TAXES_DIM
(
  WHOLDING_TAXES_KEY  NUMBER PRIMARY KEY,
  WHTAX_ID            NUMBER(5)                 NOT NULL,
  GIBR_GFUN_FUND_CD   VARCHAR2(3 BYTE)          NOT NULL,
  GIBR_BRANCH_CD      VARCHAR2(2 BYTE)          NOT NULL,
  WHTAX_CODE          NUMBER(2)                 NOT NULL,
  WHTAX_DESC          VARCHAR2(100 BYTE)        NOT NULL,
  IND_CORP_TAG        VARCHAR2(1 BYTE)          NOT NULL,
  PERCENT_RATE        NUMBER(5,3)               NOT NULL,
  BIR_TAX_CD          VARCHAR2(10 BYTE)         NOT NULL,
  START_DT            DATE                      NOT NULL,
  END_DT              DATE,
  GL_ACCT_ID          NUMBER(6)                 NOT NULL,
  REMARKS             VARCHAR2(4000 BYTE),
  USER_ID             VARCHAR2(8 BYTE)          NOT NULL,
  LAST_UPDATE         DATE                      NOT NULL,
  CPI_REC_NO          NUMBER(12),
  CPI_BRANCH_CD       VARCHAR2(2 BYTE),
  SL_TYPE_CD          VARCHAR2(2 BYTE),
  RECON_SW            VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_WHOLDING_TAXES_DIM;

INSERT INTO BI_WHOLDING_TAXES_DIM SELECT ROWNUM TAXES_KEY, A.* FROM GIAC_TAXES A

--BI_WHOLDING_TAXES_DIM END

--######################
--######################

--BI_TRAN_DIM START

DROP TABLE BIADMIN.BI_TRAN_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_TRAN_DIM
(
  TRAN_KEY         NUMBER PRIMARY KEY,
  TRAN_ID          NUMBER(12)                   NOT NULL,
  GFUN_FUND_CD     VARCHAR2(3 BYTE)             NOT NULL,
  GIBR_BRANCH_CD   VARCHAR2(2 BYTE)             NOT NULL,
  TRAN_DATE        DATE                         NOT NULL,
  TRAN_FLAG        VARCHAR2(1 BYTE)             NOT NULL,
  TRAN_YEAR        NUMBER(4),
  TRAN_MONTH       NUMBER(2),
  TRAN_SEQ_NO      NUMBER(6),
  TRAN_CLASS       VARCHAR2(3 BYTE),
  TRAN_CLASS_NO    NUMBER(10),
  JV_NO            NUMBER(6),
  JV_PREF_SUFF     VARCHAR2(2 BYTE),
  JV_ID            NUMBER(6),
  POSTING_DATE     DATE,
  PARTICULARS      VARCHAR2(2000 BYTE),
  USER_ID          VARCHAR2(8 BYTE)             NOT NULL,
  LAST_UPDATE      DATE                         NOT NULL,
  CPI_REC_NO       NUMBER(12),
  CPI_BRANCH_CD    VARCHAR2(2 BYTE),
  AE_TAG           VARCHAR2(1 BYTE),
  JV_TRAN_TAG      VARCHAR2(2 BYTE),
  JV_TRAN_TYPE     VARCHAR2(3 BYTE),
  JV_TRAN_MM       NUMBER(2),
  JV_TRAN_YY       NUMBER(4),
  UPLOAD_TAG       VARCHAR2(1 BYTE),
  CREATE_BY        VARCHAR2(8 BYTE),
  SAP_INC_TAG      VARCHAR2(1 BYTE),
  REMARKS          VARCHAR2(2000 BYTE),
  SAP_UPLOAD_STAT  VARCHAR2(1 BYTE),
  REF_JV_NO        VARCHAR2(15 BYTE),
  CLOSING_DATE     DATE,
  TB_EXCLUDE_TAG   VARCHAR2(1 BYTE),
  JV_PREF          VARCHAR2(2 BYTE),
  JV_SEQ_NO        NUMBER(12)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

TRUNCATE TABLE BI_TRAN_DIM;

INSERT INTO BI_TRAN_DIM SELECT ROWNUM TRAN_KEY, A.* FROM GIAC_ACCTRANS A
  
--BI_TRAN_DIM END

--######################
--######################

--BI_ACCT_BRANCH_DIM START

ALTER TABLE BIADMIN.BI_ACCT_BRANCH_DIM
 DROP PRIMARY KEY CASCADE;
DROP TABLE BIADMIN.BI_ACCT_BRANCH_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_ACCT_BRANCH_DIM
(
  BRANCH_KEY      NUMBER,
  FUND_CD         VARCHAR2(3 BYTE)              NOT NULL,
  BRANCH_CD       VARCHAR2(12 BYTE)             NOT NULL,
  ACCT_BRANCH_CD  NUMBER(2)                     NOT NULL,
  FUND_NAME       VARCHAR2(50 BYTE)             NOT NULL,
  BRANCH_NAME     VARCHAR2(50 BYTE)             NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIADMIN.BI_ACCT_BRANCH_DIM ADD (
  PRIMARY KEY
 (BRANCH_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

TRUNCATE TABLE BI_ACCT_BRANCH_DIM;

INSERT INTO BI_ACCT_BRANCH_DIM (SELECT ROWNUM branch_key,
       b.fund_cd,
       a.branch_cd,
       a.acct_branch_cd,
       b.fund_desc fund_name,
       a.branch_name FROM giac_branches a, giis_funds b
WHERE A.GFUN_FUND_CD = b.fund_cd);
  
--BI_ACCT_BRANCH_DIM END

--######################
--######################

--BI_BINDER_DIM START

ALTER TABLE BIADMIN.BI_BINDER_DIM
 DROP PRIMARY KEY CASCADE;
DROP TABLE BIADMIN.BI_BINDER_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_BINDER_DIM
(
  BINDER_KEY          NUMBER,
  FNL_BINDER_ID       NUMBER(8)                 NOT NULL,
  LINE_CD             VARCHAR2(2 BYTE)          NOT NULL,
  BINDER_YY           NUMBER(2)                 NOT NULL,
  BINDER_SEQ_NO       NUMBER(5)                 NOT NULL,
  RI_CD               NUMBER(5)                 NOT NULL,
  RI_TSI_AMT          NUMBER(16,2)              NOT NULL,
  RI_SHR_PCT          NUMBER(12,9)              NOT NULL,
  RI_PREM_AMT         NUMBER(12,2)              NOT NULL,
  RI_COMM_RT          NUMBER(12,9),
  RI_COMM_AMT         NUMBER(12,2),
  PREM_TAX            NUMBER(12,2),
  EFF_DATE            DATE,
  EXPIRY_DATE         DATE,
  BINDER_DATE         DATE,
  ATTENTION           VARCHAR2(50 BYTE),
  CONFIRM_NO          VARCHAR2(20 BYTE),
  CONFIRM_DATE        DATE,
  REVERSE_DATE        DATE,
  ACC_ENT_DATE        DATE,
  ACC_REV_DATE        DATE,
  USER_ID             VARCHAR2(8 BYTE),
  LAST_UPDATE         DATE,
  CPI_REC_NO          NUMBER(12),
  CPI_BRANCH_CD       VARCHAR2(2 BYTE),
  REPLACED_FLAG       VARCHAR2(1 BYTE),
  BNDR_PRINT_DATE     DATE,
  BNDR_PRINTED_CNT    NUMBER(3),
  CREATE_BINDER_DATE  DATE,
  ENDT_TEXT           VARCHAR2(2000 BYTE),
  REF_BINDER_NO       VARCHAR2(30 BYTE),
  POLICY_ID           NUMBER(12),
  ISS_CD              VARCHAR2(2 BYTE),
  RI_PREM_VAT         NUMBER(12,2),
  RI_COMM_VAT         NUMBER(12,2),
  RI_WHOLDING_VAT     NUMBER(12,2),
  BNDR_STAT_CD        VARCHAR2(3 BYTE),
  RELEASE_DATE        DATE,
  RELEASED_BY         VARCHAR2(20 BYTE),
  ARC_EXT_DATA        VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIADMIN.BI_BINDER_DIM ADD (
  PRIMARY KEY
 (BINDER_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
  
--BI_BINDER_DIM END

--######################
--######################

--BI_ADVS_FLA_DIM START

DROP TABLE BIADMIN.BI_ADVS_FLA_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_ADVS_FLA_DIM
(
  ADVS_FLA_KEY    NUMBER PRIMARY KEY,
  FLA_ID          NUMBER(12)                    NOT NULL,
  CLAIM_ID        NUMBER(12)                    NOT NULL,
  GRP_SEQ_NO      NUMBER(4)                     NOT NULL,
  RI_CD           NUMBER(5)                     NOT NULL,
  LINE_CD         VARCHAR2(2 BYTE)              NOT NULL,
  LA_YY           NUMBER(2)                     NOT NULL,
  FLA_SEQ_NO      NUMBER(7)                     NOT NULL,
  USER_ID         VARCHAR2(8 BYTE)              NOT NULL,
  LAST_UPDATE     DATE,
  FLA_DATE        DATE,
  PAID_SHR_AMT    NUMBER(16,2),
  NET_SHR_AMT     NUMBER(16,2),
  ADV_SHR_AMT     NUMBER(16,2),
  FLA_TITLE       VARCHAR2(500 BYTE),
  FLA_HEADER      VARCHAR2(500 BYTE),
  FLA_FOOTER      VARCHAR2(2000 BYTE),
  SHARE_TYPE      VARCHAR2(1 BYTE),
  PRINT_SW        VARCHAR2(1 BYTE)              NOT NULL,
  CANCEL_TAG      VARCHAR2(1 BYTE),
  ADV_FLA_ID      NUMBER(12),
  ACCT_TRTY_TYPE  NUMBER(2),
  CPI_REC_NO      NUMBER(12),
  CPI_BRANCH_CD   VARCHAR2(2 BYTE),
  LOSS_SHR_AMT    NUMBER(16,2),
  EXP_SHR_AMT     NUMBER(16,2)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--BI_ADVS_FLA_DIM END

--######################
--######################

--BI_CLM_RECOVERY_DIM START

ALTER TABLE BIADMIN.BI_CLM_RECOVERY_DIM
 DROP PRIMARY KEY CASCADE;
DROP TABLE BIADMIN.BI_CLM_RECOVERY_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CLM_RECOVERY_DIM
(
  CLM_RECOVERY_KEY     NUMBER,
  RECOVERY_ID          NUMBER(12)               NOT NULL,
  CLAIM_ID             NUMBER(12)               NOT NULL,
  LINE_CD              VARCHAR2(2 BYTE)         NOT NULL,
  REC_YEAR             NUMBER(4)                NOT NULL,
  REC_SEQ_NO           NUMBER(3)                NOT NULL,
  REC_TYPE_CD          VARCHAR2(5 BYTE)         NOT NULL,
  RECOVERABLE_AMT      NUMBER(16,2),
  RECOVERED_AMT        NUMBER(16,2),
  TP_ITEM_DESC         VARCHAR2(500 BYTE),
  PLATE_NO             VARCHAR2(20 BYTE),
  CURRENCY_CD          NUMBER(2),
  CONVERT_RATE         NUMBER(12,9),
  LAWYER_CLASS_CD      VARCHAR2(2 BYTE),
  LAWYER_CD            NUMBER(12),
  CPI_REC_NO           NUMBER(12),
  CPI_BRANCH_CD        VARCHAR2(2 BYTE),
  USER_ID              VARCHAR2(8 BYTE)         NOT NULL,
  LAST_UPDATE          DATE                     NOT NULL,
  CANCEL_TAG           VARCHAR2(2 BYTE),
  ISS_CD               VARCHAR2(2 BYTE)         NOT NULL,
  DEMAND_LETTER_DATE   DATE,
  DEMAND_LETTER_DATE2  DATE,
  DEMAND_LETTER_DATE3  DATE,
  REC_FILE_DATE        DATE,
  TP_DRIVER_NAME       VARCHAR2(100 BYTE),
  TP_DRVR_ADD          VARCHAR2(1000 BYTE),
  TP_PLATE_NO          VARCHAR2(10 BYTE),
  CASE_NO              VARCHAR2(100 BYTE),
  COURT                VARCHAR2(200 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIADMIN.BI_CLM_RECOVERY_DIM ADD (
  PRIMARY KEY
 (CLM_RECOVERY_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

--BI_CLM_RECOVERY_DIM END

--######################
--######################

--BI_REINSURER_DIM START

ALTER TABLE BIADMIN.BI_REINSURER_DIM
 DROP PRIMARY KEY CASCADE;
DROP TABLE BIADMIN.BI_REINSURER_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_REINSURER_DIM
(
  RI_KEY            NUMBER,
  RI_CD             NUMBER(5)                   NOT NULL,
  LOCAL_FOREIGN_SW  VARCHAR2(1 BYTE)            NOT NULL,
  RI_STATUS_CD      NUMBER(2)                   NOT NULL,
  RI_SNAME          VARCHAR2(15 BYTE),
  RI_NAME           VARCHAR2(50 BYTE),
  MAIL_ADDRESS1     VARCHAR2(50 BYTE),
  MAIL_ADDRESS2     VARCHAR2(50 BYTE),
  MAIL_ADDRESS3     VARCHAR2(50 BYTE),
  BILL_ADDRESS1     VARCHAR2(50 BYTE),
  BILL_ADDRESS2     VARCHAR2(50 BYTE),
  BILL_ADDRESS3     VARCHAR2(50 BYTE),
  PHONE_NO          VARCHAR2(40 BYTE),
  FAX_NO            VARCHAR2(40 BYTE),
  TELEX_NO          VARCHAR2(40 BYTE),
  THRU_RI_CD        NUMBER(5),
  CONTACT_PERS      VARCHAR2(50 BYTE),
  ATTENTION         VARCHAR2(50 BYTE),
  INT_TAX_RT        NUMBER(7,4),
  PRES_AND_XOS      VARCHAR2(280 BYTE),
  LISCENCE_NO       VARCHAR2(15 BYTE),
  MAX_LINE_NET_RET  VARCHAR2(160 BYTE),
  FACILITIES        LONG,
  MAX_NET_RET       NUMBER(16,2),
  TOT_ASSET         NUMBER(16,2),
  TOT_LIAB          NUMBER(16,2),
  TOT_NET_WORTH     NUMBER(16,2),
  CAPITAL_STRUC     NUMBER(7,4),
  RI_TYPE           VARCHAR2(2 BYTE),
  EFF_DATE          DATE,
  EXPIRY_DATE       DATE,
  USER_ID           VARCHAR2(8 BYTE)            NOT NULL,
  LAST_UPDATE       DATE                        NOT NULL,
  REMARKS           VARCHAR2(4000 BYTE),
  CPI_REC_NO        NUMBER(12),
  CPI_BRANCH_CD     VARCHAR2(2 BYTE),
  CP_NO             VARCHAR2(40 BYTE),
  SUN_NO            VARCHAR2(40 BYTE),
  SMART_NO          VARCHAR2(40 BYTE),
  GLOBE_NO          VARCHAR2(40 BYTE),
  INPUT_VAT_RATE    NUMBER(5,3),
  RI_TIN            VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    15
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIADMIN.BI_REINSURER_DIM ADD (
  PRIMARY KEY
 (RI_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

--BI_REINSURER_DIM END

--######################
--######################

--BI_ADVICE_DIM START

ALTER TABLE BIADMIN.BI_ADVICE_DIM
 DROP PRIMARY KEY CASCADE;
DROP TABLE BIADMIN.BI_ADVICE_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_ADVICE_DIM
(
  ADVICE_KEY      NUMBER,
  ADVICE_ID       NUMBER(12)                    NOT NULL,
  CLAIM_ID        NUMBER(12)                    NOT NULL,
  LINE_CD         VARCHAR2(2 BYTE)              NOT NULL,
  ISS_CD          VARCHAR2(2 BYTE)              NOT NULL,
  ADVICE_YEAR     NUMBER(4)                     NOT NULL,
  ADVICE_SEQ_NO   NUMBER(6)                     NOT NULL,
  ADVICE_FLAG     VARCHAR2(1 BYTE)              NOT NULL,
  USER_ID         VARCHAR2(8 BYTE)              NOT NULL,
  LAST_UPDATE     DATE                          NOT NULL,
  ADVISE_AMT      NUMBER(16,2),
  NET_AMT         NUMBER(16,2),
  PAID_AMT        NUMBER(16,2),
  CPI_REC_NO      NUMBER(12),
  CPI_BRANCH_CD   VARCHAR2(2 BYTE),
  APPRVD_TAG      VARCHAR2(1 BYTE),
  BATCH_CSR_ID    NUMBER(12),
  ADV_FLA_ID      NUMBER(12),
  CURRENCY_CD     NUMBER(2),
  CONVERT_RATE    NUMBER(12,9),
  ADVICE_DATE     DATE,
  PAID_FCURR_AMT  NUMBER(16,2),
  NET_FCURR_AMT   NUMBER(16,2),
  ADV_FCURR_AMT   NUMBER(16,2),
  BATCH_DV_ID     NUMBER(12),
  REMARKS         VARCHAR2(4000 BYTE),
  PAYEE_REMARKS   VARCHAR2(500 BYTE),
  ORIG_CURR_RATE  NUMBER(12,9),
  ORIG_CURR_CD    NUMBER(2)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIADMIN.BI_ADVICE_DIM ADD (
  PRIMARY KEY
 (ADVICE_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

--BI_ADVICE_DIM END

--######################
--######################

--BI_CLAIM_DIM START

ALTER TABLE BIADMIN.BI_CLAIMS_DIM
 DROP PRIMARY KEY CASCADE;
DROP TABLE BIADMIN.BI_CLAIMS_DIM CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CLAIMS_DIM
(
  CLAIM_KEY  NUMBER,
  CLAIM_ID   NUMBER(12)                         NOT NULL,
  CLAIM_NO   VARCHAR2(26 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIADMIN.BI_CLAIMS_DIM ADD (
  PRIMARY KEY
 (CLAIM_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


--BI_CLAIM_DIM END

--######################
--######################