DROP TABLE BIADMIN.BI_CLAIMS_AGENT_FACT CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CLAIMS_AGENT_FACT
(
  LOSS_DATE              NUMBER,
  FILE_DATE              NUMBER,
  EFFECTIVITY_DATE       NUMBER,
  CLOSE_DATE             NUMBER,
  LOSS_AMOUNT            NUMBER,
  EXPENSE_AMOUNT         NUMBER,
  LOSS_RETENTION         NUMBER,
  EXPENSE_RETENTION      NUMBER,
  LOSS_PROPOR_TREATY     NUMBER,
  EXP_PROPOR_TREATY      NUMBER,
  LOSS_FACULTATIVE       NUMBER,
  EXP_FACULTATIVE        NUMBER,
  LOSS_NONPROPOR_TREATY  NUMBER,
  EXP_NONPROPOR_TREATY   NUMBER,
  CLAIM_ID               NUMBER(12),
  ASSD_NO                NUMBER(12),
  PARENT_NO              NUMBER(12),
  ISSUE_YY               NUMBER(2),
  RENEW_NO               NUMBER(2),
  PERIL_CD               NUMBER(5),
  POL_SEQ_NO             NUMBER(10),
  LINE_CD                VARCHAR2(2 BYTE),
  ISS_CD                 VARCHAR2(2 BYTE),
  POL_ISS_CD             VARCHAR2(2 BYTE),
  INTM_TYPE              VARCHAR2(2 BYTE),
  CLM_STAT_CD            VARCHAR2(2 BYTE),
  OLD_STAT_CD            VARCHAR2(2 BYTE),
  PARENT_NAME            VARCHAR2(150 BYTE),
  CLAIM_NO               VARCHAR2(30 BYTE),
  POLICY_NO              VARCHAR2(30 BYTE),
  SUBLINE_CD             VARCHAR2(10 BYTE),
  LINE_CODE              NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
