DROP TABLE BIADMIN.BI_COLLECTION_TAX_FACT CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_COLLECTION_TAX_FACT
(
  COLLECTION_CODE    NUMBER(12)                 NOT NULL,
  LINE_CODE          NUMBER(12)                 NOT NULL,
  BRANCH_CODE        NUMBER(12),
  AGENT_CODE         NUMBER(12),
  ASSURED_CODE       NUMBER(12),
  POLICY_NO          VARCHAR2(50 BYTE),
  ENDORSEMENT_NO     VARCHAR2(50 BYTE),
  TRAN_DATE          NUMBER(12),
  POS_DATE           NUMBER(12),
  PREMIUM_AMOUNT     NUMBER(12,2),
  TAX_AMOUNT         NUMBER(12,2),
  EVAT               NUMBER(12,2),
  LOCAL_GOV_TAX      NUMBER(12,2),
  DOC_STAMPS         NUMBER(12,2),
  FIRE_SERVICE_TAX   NUMBER(12,2),
  OTHER_CHARGES      NUMBER(12,2),
  BOOK_TAG           VARCHAR2(1 BYTE),
  COLLECTION_AMOUNT  NUMBER,
  GIBR_BRANCH_CODE   NUMBER(12),
  TRAN_FLAG          VARCHAR2(1 BYTE),
  BILL_NO            VARCHAR2(100 BYTE),
  TRAN_CLASS         VARCHAR2(5 BYTE),
  COMMISSION_AMT     NUMBER,
  WTAX_AMT           NUMBER,
  INPUT_VAT_AMT      NUMBER,
  POLICY_ID          NUMBER(12),
  DUE_DATE           NUMBER(12),
  EFF_DATE           NUMBER(12),
  OR_DATE            NUMBER(12),
  INCEPT_DATE        NUMBER(12),
  POL_FLAG           VARCHAR2(100 BYTE),
  AGE                NUMBER,
  INVOICE_PREM_AMT   NUMBER(12,2)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
