DROP TABLE BIADMIN.BI_CLAIMS_BRDRX_FACT CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CLAIMS_BRDRX_FACT
(
  CLAIM_ID          NUMBER(12),
  ITEM_NO           NUMBER(9),
  POLICY_NO         VARCHAR2(50 BYTE)           NOT NULL,
  CLAIM_NO          VARCHAR2(50 BYTE),
  ISS_CODE          VARCHAR2(12 BYTE),
  BRANCH_CODE       NUMBER(12),
  RI_CODE           NUMBER(12),
  LINE_CODE         VARCHAR2(12 BYTE),
  SUBLINE_CODE      VARCHAR2(12 BYTE),
  LOSS_YEAR         NUMBER(9),
  ASSURED_CODE      NUMBER(12),
  LOSS_DATE         NUMBER(12),
  CLAIM_FILE_DATE   NUMBER(12),
  INCEPT_DATE       NUMBER(12),
  EXPIRY_DATE       NUMBER(12),
  POL_ISS_CD        VARCHAR2(12 BYTE),
  ISSUE_YY          NUMBER(12),
  POL_SEQ_NO        NUMBER(12),
  RENEW_NO          NUMBER(12),
  PERIL_CD          NUMBER(12),
  LOSS_CAT_CD       VARCHAR2(12 BYTE),
  ANN_TSI_AMT       NUMBER(16,2),
  DIST_SW           VARCHAR2(10 BYTE),
  CONVERT_RATE      NUMBER(12,2),
  LOSS_RESERVE      NUMBER(12,2),
  LOSSES_PAID       NUMBER(12,2),
  EXPENSE_RESERVE   NUMBER(12,2),
  EXPENSES_PAID     NUMBER(12,2),
  GRP_ITEM_NO       NUMBER(12),
  CLM_RES_HIST_ID   NUMBER(12),
  GRP_ITEM_TITLE    VARCHAR2(50 BYTE),
  CONTROL_CD        NUMBER(12),
  CONTROL_TYPE_CD   NUMBER(12),
  BOOKING_YEAR      NUMBER(4),
  BOOKING_MONTH     VARCHAR2(10 BYTE),
  DATE_PAID         NUMBER(12),
  POSTING_DATE      NUMBER(12),
  CANCEL_TAG        VARCHAR2(1 BYTE),
  CANCEL_DATE       NUMBER(12),
  TRAN_ID           NUMBER(12),
  TRAN_DATE         NUMBER(12),
  BRDRX_TYPE        VARCHAR2(100 BYTE),
  CLOSE_DATE        NUMBER(12),
  CLOSE_DATE2       NUMBER(12),
  CURRENCY_RATE     NUMBER(4),
  INTM_NO           NUMBER(12),
  INTM_NAME         VARCHAR2(4000 BYTE),
  LOSS_CAT_DES      VARCHAR2(25 BYTE),
  CLAIM_STATUS      VARCHAR2(30 BYTE),
  ITEM_TITLE        VARCHAR2(4000 BYTE),
  CRED_BRANCH_CODE  NUMBER(12),
  REC_COUNT         NUMBER,
  ACC_POSTING_DATE  NUMBER(12),
  ACC_DATE_PAID     NUMBER(12),
  ACC_TRAN_ID       NUMBER(12),
  BUSS_SOURCE       NUMBER(10),
  BOOKING_DATE      NUMBER(12)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
