CREATE TABLE BIADMIN.BI_CLAIMS_LP_AGENT_FACT
(
  CLAIM_REC         NUMBER(12),
  POLICY_ID         NUMBER,
  LINE_CODE         NUMBER,
  LOSSES_PAID       NUMBER(16,5),
  EXPENSES_PAID     NUMBER(16,5),
  SHR_PCT           NUMBER,
  CLAIM_ID          NUMBER(12)                  NOT NULL,
  BRANCH_CODE       NUMBER(12),
  AGENT_CODE        NUMBER(12),
  ASSURED_CODE      NUMBER(12),
  TRAN_ID           NUMBER(12),
  INTM_NO           NUMBER(12),
  CONVERT_RATE      NUMBER(12,9),
  LOSS_RESERVE      NUMBER(16,5),
  EXPENSE_RESERVE   NUMBER(16,5),
  CLM_RES_HIST_ID   NUMBER(5),
  PERIL_CD          NUMBER(5),
  ITEM_NO           NUMBER(9),
  CANCEL_TAG        VARCHAR2(1 BYTE),
  DIST_SW           VARCHAR2(1 BYTE),
  POL_ISS_CD        VARCHAR2(2 BYTE),
  LOSS_CAT_DES      VARCHAR2(25 BYTE),
  CLAIM_NO          VARCHAR2(26 BYTE),
  POLICY_NO         VARCHAR2(30 BYTE),
  CLAIM_STATUS      VARCHAR2(30 BYTE),
  CLAIM_STATUS_GRP  VARCHAR2(30 BYTE),
  TRAN_DATE         NUMBER,
  TRAN_FLAG         VARCHAR2(4000 BYTE),
  INTM_NAME         VARCHAR2(4000 BYTE),
  ISSUE_SOURCE      VARCHAR2(7 BYTE),
  EFFECTIVITY_DATE  NUMBER,
  LOSS_DATE         NUMBER,
  DATE_PAID         NUMBER,
  FILE_DATE         NUMBER,
  CANCEL_DATE       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIADMIN.BI_CLAIMS_LP_AGENT_FACT ADD (
  PRIMARY KEY
 (CLAIM_REC)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE BIADMIN.BI_CLAIMS_LP_AGENT_FACT ADD (
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK1 
 FOREIGN KEY (LINE_CODE) 
 REFERENCES BIADMIN.BI_LINE_DIM (LINE_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK2 
 FOREIGN KEY (BRANCH_CODE) 
 REFERENCES BIADMIN.BI_BRANCH_DIM (BRANCH_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK3 
 FOREIGN KEY (AGENT_CODE) 
 REFERENCES BIADMIN.BI_AGENT_DIM (AGENT_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK4 
 FOREIGN KEY (ASSURED_CODE) 
 REFERENCES BIADMIN.BI_ASSURED_DIM (ASSURED_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK5 
 FOREIGN KEY (TRAN_DATE) 
 REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK6 
 FOREIGN KEY (LOSS_DATE) 
 REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK7 
 FOREIGN KEY (FILE_DATE) 
 REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK8 
 FOREIGN KEY (DATE_PAID) 
 REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE),
  CONSTRAINT BI_CLAIMS_LP_AGENT_FACT_FK9 
 FOREIGN KEY (CANCEL_DATE) 
 REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE));

