DROP TABLE BIADMIN.BI_CLAIMS_FACT CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CLAIMS_FACT
(
  CLAIM_SEQNO            NUMBER(12),
  CLAIM_ID               NUMBER(12),
  LINE_SUBLINE_CODE      NUMBER(12),
  ASSD_NO                NUMBER(12),
  CLAIM_NO               VARCHAR2(24 BYTE),
  POLICY_NO              VARCHAR2(30 BYTE),
  ISSUE_SOURCE           VARCHAR2(7 BYTE),
  CLAIMS_BRANCH_CODE     NUMBER(12),
  CLAIM_STATUS           VARCHAR2(30 BYTE),
  EXPENSE_AMOUNT         NUMBER(16,5),
  LOSS_AMOUNT            NUMBER(16,5),
  EXP_RETENTION_AMT      NUMBER(16,5),
  EXP_PROPOR_TREATY      NUMBER(16,5),
  EXP_FACULTATIVE        NUMBER(16,5),
  EXP_NONPROPOR_TREATY   NUMBER(16,5),
  LOSS_RETENTION_AMT     NUMBER(16,5),
  LOSS_PROPOR_TREATY     NUMBER(16,5),
  LOSS_FACULTATIVE       NUMBER(16,5),
  LOSS_NONPROPOR_TREATY  NUMBER(16,5),
  LOSS_DATE              NUMBER(12),
  FILE_DATE              NUMBER(12),
  EFFECTIVITY_DATE       NUMBER(12),
  CLOSE_DATE             NUMBER(12),
  BRANCH_CODE            NUMBER(12),
  CLM_STAT_CD            VARCHAR2(2 BYTE),
  ITEM_NO                NUMBER(12),
  ITEM_TITLE             VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
