DROP TABLE BIADMIN.BI_CLAIMS_BRDRX_TAKE_UP_FACT CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_CLAIMS_BRDRX_TAKE_UP_FACT
(
  CLAIM_ID             NUMBER(12),
  CLAIM_NO             VARCHAR2(50 BYTE),
  POLICY_NO            VARCHAR2(50 BYTE)        NOT NULL,
  ANN_TSI_AMT          NUMBER,
  ASSURED_NO           NUMBER(12),
  BUSS_SOURCE          NUMBER(2),
  CLM_RES_HIST_ID      NUMBER(12),
  GROUPED_ITEM_NO      NUMBER,
  ITEM_NO              NUMBER,
  LOSS_YEAR            NUMBER(9),
  OS_EXPENSE           NUMBER(12,2),
  OS_LOSS              NUMBER(12,2),
  TRAN_FLAG            VARCHAR2(10 BYTE),
  ACCT_DATE            NUMBER(12),
  CLM_FILE_DATE        NUMBER(12),
  EXPIRY_DATE          NUMBER(12),
  INCEPT_DATE          NUMBER(12),
  LOSS_DATE            NUMBER(12),
  POSTING_DATE         NUMBER(12),
  TRAN_DATE            NUMBER(12),
  ISS_BRANCH_CODE      NUMBER(12),
  POL_ISS_BRANCH_CODE  NUMBER(12),
  LINE_CODE            NUMBER(12),
  LOSS_CAT_DES         VARCHAR2(50 BYTE),
  ITEM_TITLE           VARCHAR2(4000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
