CREATE TABLE BIADMIN.BI_CLAIMS_REG_FACT
(
  CLAIM_ID         NUMBER(12),
  CLAIM_NO         VARCHAR2(50 BYTE),
  ITEM_NO          NUMBER(9),
  POLICY_NO        VARCHAR2(50 BYTE)            NOT NULL,
  CLM_RES_HIST_ID  NUMBER(12),
  CLAIM_STATUS     VARCHAR2(30 BYTE),
  PREM_AMT         NUMBER(12,2),
  LOSS_RESERVE     NUMBER(12,2),
  LOSSES_PAID      NUMBER(12,2),
  EXPENSE_RESERVE  NUMBER(12,2),
  EXPENSES_PAID    NUMBER(12,2),
  ANN_TSI_AMT      NUMBER(16,2),
  ASSURED_CODE     NUMBER(12),
  CLAIM_FILE_DATE  NUMBER(12),
  DSP_LOSS_DATE    NUMBER(12),
  CLM_ISS_CODE     NUMBER(12),
  LOSS_DATE        NUMBER(12),
  EFF_DATE         NUMBER(12),
  EXP_DATE         NUMBER(12),
  ITEM_TITLE       VARCHAR2(300 BYTE),
  AGENT            VARCHAR2(300 BYTE),
  RECOVERED_AMT    NUMBER(16,2),
  CANCEL_TAG       VARCHAR2(2 BYTE),
  CANCEL_DATE      NUMBER(12),
  POL_ISS_CODE     NUMBER(12),
  LINE_CODE        NUMBER(12)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


