ALTER TABLE BIADMIN.BI_OUTSTANDING_FACT
 DROP PRIMARY KEY CASCADE;

DROP TABLE BIADMIN.BI_OUTSTANDING_FACT CASCADE CONSTRAINTS;

CREATE TABLE BIADMIN.BI_OUTSTANDING_FACT
(
  CLAIM_REC        NUMBER(12),
  CLAIM_ID         NUMBER(12)                   NOT NULL,
  POLICY_NO        VARCHAR2(30 BYTE),
  POLICY_ID        NUMBER,
  CLAIM_NO         VARCHAR2(26 BYTE),
  LINE_CODE        NUMBER,
  BRANCH_CODE      NUMBER(12),
  AGENT_CODE       NUMBER(12),
  ASSURED_CODE     NUMBER(12),
  PERIL_CD         NUMBER(5),
  POSTING_DATE     NUMBER,
  TRAN_DATE        NUMBER,
  LOSS_DATE        NUMBER,
  FILE_DATE        NUMBER,
  BOOKING_DATE     NUMBER,
  TRAN_FLAG        VARCHAR2(100 BYTE),
  OS_LOSS          NUMBER(16,5),
  OS_EXPENSE       NUMBER(16,5),
  SHR_PCT          NUMBER(12,9),
  SHARE_TYPE       VARCHAR2(100 BYTE),
  DATE_PAID        NUMBER,
  LOSS_RESERVE     NUMBER(16,5),
  LOSSES_PAID      NUMBER(16,5),
  EXPENSE_RESERVE  NUMBER(16,5),
  EXPENSES_PAID    NUMBER(16,5),
  CLOSE_DATE       NUMBER,
  CLOSE_DATE2      NUMBER,
  CANCEL_TAG       VARCHAR2(1 BYTE),
  CANCEL_DATE      NUMBER,
  TAKEN_UP         CHAR(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BIADMIN.BI_OUTSTANDING_FACT_IDX2 ON BIADMIN.BI_OUTSTANDING_FACT
(BOOKING_DATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BIADMIN.BI_OUTSTANDING_FACT_IDX3 ON BIADMIN.BI_OUTSTANDING_FACT
(CLOSE_DATE2)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BIADMIN.BI_OUTSTANDING_FACT_IDX4 ON BIADMIN.BI_OUTSTANDING_FACT
(TAKEN_UP)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--  There is no statement for index BIADMIN.SYS_C0012827.
--  The object is created when the parent object is created.

ALTER TABLE BIADMIN.BI_OUTSTANDING_FACT ADD (
  PRIMARY KEY
  (CLAIM_REC)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE BIADMIN.BI_OUTSTANDING_FACT ADD (
  CONSTRAINT BI_OUTSTANDING_FACT_FK1 
  FOREIGN KEY (LINE_CODE) 
  REFERENCES BIADMIN.BI_LINE_DIM (LINE_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK10 
  FOREIGN KEY (DATE_PAID) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK11 
  FOREIGN KEY (CLOSE_DATE) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK12 
  FOREIGN KEY (CLOSE_DATE2) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK14 
  FOREIGN KEY (CANCEL_DATE) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK2 
  FOREIGN KEY (BRANCH_CODE) 
  REFERENCES BIADMIN.BI_BRANCH_DIM (BRANCH_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK3 
  FOREIGN KEY (AGENT_CODE) 
  REFERENCES BIADMIN.BI_AGENT_DIM (AGENT_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK4 
  FOREIGN KEY (ASSURED_CODE) 
  REFERENCES BIADMIN.BI_ASSURED_DIM (ASSURED_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK5 
  FOREIGN KEY (POSTING_DATE) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK6 
  FOREIGN KEY (TRAN_DATE) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK7 
  FOREIGN KEY (LOSS_DATE) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK8 
  FOREIGN KEY (FILE_DATE) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE,
  CONSTRAINT BI_OUTSTANDING_FACT_FK9 
  FOREIGN KEY (BOOKING_DATE) 
  REFERENCES BIADMIN.BI_TIME_DIM (TIME_CODE)
  ENABLE VALIDATE);
