CREATE TABLE CPI.BI_LINE_DIM2
(
  LINE_CODE     NUMBER(12),
  LINE_NAME     VARCHAR2(50 BYTE)               NOT NULL,
  SUBLINE_NAME  VARCHAR2(50 BYTE)               NOT NULL,
  PERIL_NAME    VARCHAR2(50 BYTE),
  PERIL_SNAME   VARCHAR2(4 BYTE),
  PERIL_TYPE    VARCHAR2(1 BYTE)
)